name: Refactor
description: New code refactor
title: "[REFACTOR]: "
labels: ["refactor"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to send new refactor idea!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: How can we improve our code?
      description: Tell us what's your suggestion?
      value: "My suggestion is..."
    validations:
      required: true
