name: Test
description: New test improvement
title: "[TEST]: "
labels: ["test"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to helps us improve the tests!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: How can we improve our tests?
      description: Tell us what's your suggestion?
      value: "My suggestion is..."
    validations:
      required: true
