name: Deploy Gitub Pages

on:
  pull_request:
    branches: 
      - master

jobs:
  check-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint
